### ISSUE TITLE
User data storage

### ISSUE THREAD

**Issue by jnordberg** [steemit/steemitapi#8]
We need to store user emails and phone numbers for accounts created when users signup via sc2/faucet

This means that faucet must be capable of taking a rpc endpoint that it should hit with that data once the user has signed up, also faucet should remove its own records of the data once the endpoint has been successfully called.

Endpoints

`set_user_data <account> <{email, phone}>`
requires auth, signed by account or an admin_role

`get_user_data <account>`
requires auth, signed by account or an admin_role

`is_email_registered <email>` responds with true if email is in db, otherwise false
requires auth, signed by an admin_role

**Comment by jnordberg** [comment]
cc @bonustrack

**Comment by sneak** [comment]
lookup_email should take an email address and return bool and should probably be called is_email_registered

**Comment by jnordberg** [comment]
right, updated

**Comment by bonustrack** [comment]
Ok, on the `faucet` we will check if email already exist on steemit db using `is_email_registered` when user attempt to signup. And we will use `set_user_data` only when user been through all the process and created a Steem account then we will delete user data from `faucet` db. Can you confirm that?
Is there a public endpoint for `steemitapi` or an ETA for it?

**Comment by jnordberg** [comment]
> Ok, on the faucet we will check if email already exist on steemit db using is_email_registered when user attempt to signup. And we will use set_user_data only when user been through all the process and created a Steem account then we will delete user data from faucet db. Can you confirm that?

Yep, that sounds right. Let me know if you need any additional endpoints, `is_phone_registered` maybe?

> Is there a public endpoint for steemitapi or an ETA for it?

Not yet, we are working on getting that out this week

**Comment by bonustrack** [comment]
Ok thank you. Good catch @jnordberg we will need `is_phone_registered` too.
